version: '2'

services:
  solr:
    image: solr:7.2.1
    ports:
     - "8986:8983"
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - cmp269
    volumes:
      - ./mycores:/opt/solr/server/solr/mycores      

  ipython:
    image: ipython/scipyserver
    ports: 
      - "8888:8888"
    environment:
      PASSWORD: "cmp269"
      http_proxy:
      https_proxy:
    links:
      - solr
    volumes:
      - ./notebooks:/notebooks
