version: '2'

services:
  solr:
    image: solr:7.2.1
    ports:
     - "8983:8983"
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - cmp269

  ipython:
    image: ipython/scipyserver
    ports: 
      - "8888:8888"
    environment:
      PASSWORD: cmp269
    links:
      - solr

  python:
    image: python:3.5
    volumes:
      - ./:/cmp269
    command: tail -f /dev/null

